#!/bin/sh
[ -f $HOME/packages/screen/etc/`hostname` ] && \
	cat $HOME/packages/screen/etc/rc $HOME/packages/screen/etc/`hostname` > $HOME/.tscreenrc || \
	cp $HOME/packages/screen/etc/rc $HOME/.tscreenrc
